version: 0.2

phases:
  install:
    commands:
      - cd lambda/custom
      - npm install
  build:
    commands:
      - npm test
      - npm run build-aws-resource
artifacts:
  files:
    - lambda/custom/kilcreggan-ferry-alexa-skill.zip
    - name
  discard-paths: yes
